language: node_js
node_js:
  - "12" # version of node.js
dist: trusty
services: # service needed
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci  PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
  install:
    - npm install
    - npm run build # run frontend
  script:
    - nohup npm run start & # run backend
    - sleep 5
    - npm run test