language: node_js
node_js:
  - "13" # version of node.js
dist: trusty # virtual machine, this is a specific version of linux
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci  PORT=3000

cache: # cache means we ask travis to store those things
  directories:
    - node_modules # travis do not know what is node_modules,
    # so we need to tell it
    - client/node_modules
install:
  - npm install # tell travis how to install node_modules
  - npm run build # build react app
script:
  - nohup npm run start &
  - sleep 5 # wait for 5 seconds to start the server
  - npm run test # then run the test
